### ISSUE TITLE
Flatten JSON

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-dev-functions#13]
Hey,
The function is fully updated within my account.
I am producing the following JSON:
```
{
    "count": 2,
    "has_next": false,
    "page": 1,
    "results": {
        "test":"test2"
    }
}
```

The results I get:

```
{
  "count": 2,
  "has_next": false,
  "page": 1,
  "test": "test2"
}
```

I expected to get:
```
{
  "count": 2,
  "has_next": false,
  "page": 1,
  "results.test": "test2"
}
```

**Comment by John-Memphis** [comment]
{
  "messages": [
    {
      "headers": {},
      "payload": "{\"count\":2,\"has_next\":false,\"page\":1,\"results.test\":\"test2\"}",
      "error": ""
    }
  ],
  "failed_messages": null,
  "logs": "START RequestId: 699197f7-6a9a-4100-a6c9-61b66dc86ab4 Version: $LATEST\nEND RequestId: 699197f7-6a9a-4100-a6c9-61b66dc86ab4\nREPORT RequestId: 699197f7-6a9a-4100-a6c9-61b66dc86ab4\tDuration: 1.61 ms\tBilled Duration: 49 ms\tMemory Size: 128 MB\tMax Memory Used: 15 MB\tInit Duration: 47.01 ms\t\n",
  "error": ""
}

**Comment by John-Memphis** [comment]
That's what I'm getting from cloud
![image](https://github.com/memphisdev/memphis-dev-functions/assets/136013599/3efa8603-8636-446a-a344-a999f90d4fe7)


@yanivbh1

**Comment by John-Memphis** [comment]
For future reference, as of 12/18/2023 when this was reported, when a function was attached to a station, it needed to be deleted and then re-added in order for the function to update. flatten_json was did not have this bug at the time.
